### ISSUE TITLE
"color_mode: hs" not taken into account with RGB(W) lights

### ISSUE THREAD

**Issue by jmbertho** [shmuelzon/home-assistant-floor-plan#103]
**Describe the bug**
Some of my lights seem to be using color_mode: hs, which doesn't work with the generated yaml content.

Example of a light :
effect_list: night_mode, white_mode, 0, 1, 2, 3, 4, 5, 6, 7, 8
supported_color_modes: hs
effect: null
color_mode: hs
brightness: 255
hs_color: 0, 0
rgb_color: 255, 255, 255
xy_color: 0.323, 0.329

and the yaml only reacts to "${COLOR_MODE === 'color_temp' || (COLOR_MODE === 'rgb' ..."

**Expected behavior**
Would it be possible to update the yaml code in order to also support hs as color_mode ?

**Additional context**
... or maybe I can force these lights to a different mode than hs ? But couldn't figure how.

**Comment by shmuelzon** [comment]
Hey,

That condition should only be true for when the light is in a white color mode meaning different color temperatures of white. While it would still be a problem from `hs` color modes, if you're trying to see a colored light, it should still appear.
In any case, can you confirm that changing the YAML from something like
```yaml
      state_image:
        'on': >-
          ${COLOR_MODE === 'color_temp' || (COLOR_MODE === 'rgb' && LIGHT_COLOR && LIGHT_COLOR[0] == 0 && LIGHT_COLOR[1] == 0) ?
```
to
```yaml
      state_image:
        'on': >-
          ${COLOR_MODE === 'color_temp' || ((COLOR_MODE === 'rgb' || COLOR_MODE === 'hs') && LIGHT_COLOR && LIGHT_COLOR[0] == 0 && LIGHT_COLOR[1] == 0) ?
```
