### ISSUE TITLE
Can you please add option to set/add `opacity:` in style of state-icon?

### ISSUE THREAD

**Issue by lpt2007** [shmuelzon/home-assistant-floor-plan#119]
**Is your feature request related to a problem? Please describe.**
Can you please add option to set/add `opacity:` in style of state-icon? I like invisible lights icons  in floor-plan in center of room to turn my lights on/off:)

**Describe the solution you'd like**
example stage-icon code:
```
type: state-icon
entity: media_player.room_bedroom_tv
title: null
style:
  top: 51.07%
  left: 57.99%
  border-radius: 50%
  text-align: center
  background-color: rgba(255, 255, 255, 0.3)
  **opacity: 0**
tap_action:
  action: toggle
double_tap_action:
  action: none
hold_action:
  action: more-info
```
