### ISSUE TITLE
Light Color Overlays To Another Room

### ISSUE THREAD

**Issue by Tiagopt3** [shmuelzon/home-assistant-floor-plan#130]
**Describe the bug**
The light doesn´t stay in the room, its overlaying to another room

![Image](https://github.com/user-attachments/assets/fb4d1e78-64f6-4b12-8bc2-196c0dcdcded)

**Expected behavior**
The light must stay in the room

**Additional context**
yaml: 
```
type: picture-elements
image: /local/floorplan/base.png?version=286D74DF55634AC000F9AFB4E46ABA08
elements:
  - type: custom:config-template-card
    variables:
      LIGHT_STATE: states['light.shellyrgbw2_485519ebba83'].state
      COLOR_MODE: states['light.shellyrgbw2_485519ebba83'].attributes.color_mode
      LIGHT_COLOR: states['light.shellyrgbw2_485519ebba83'].attributes.hs_color
      BRIGHTNESS: states['light.shellyrgbw2_485519ebba83'].attributes.brightness
    entities:
      - light.shellyrgbw2_485519ebba83
    element:
      type: image
      image: /local/floorplan/transparent.png?version=56ABE4CBC175363DA0810882244B34FF
      state_image:
        'on': >-
          ${COLOR_MODE === 'color_temp' || COLOR_MODE === 'brightness' || ((COLOR_MODE === 'rgb' || COLOR_MODE === 'hs') && LIGHT_COLOR && LIGHT_COLOR[0] == 0 && LIGHT_COLOR[1] == 0) ?
          '/local/floorplan/light.shellyrgbw2_485519ebba83.png?version=30F3EB947ECDA5D9021DB4A080B596A9' :
          '/local/floorplan/light.shellyrgbw2_485519ebba83.red.png?version=25869F984FEDCAFC901EA410D9AA09FA' }
      entity: light.shellyrgbw2_485519ebba83
    style:
      filter: '${ "hue-rotate(" + (LIGHT_COLOR ? LIGHT_COLOR[0] : 0) + "deg)"}'
      opacity: '${LIGHT_STATE === ''on'' ? (BRIGHTNESS / 255) : ''100''}'
      mix-blend-mode: lighten
      pointer-events: none
      left: 50%
      top: 50%
      width: 100%
  - type: conditional
    conditions:
      - entity: switch.main_lights
        state: 'on'
    elements:
      - type: image
        tap_action:
          action: none
        hold_action:
          action: none
        entity:
          - switch.main_lights
        image: /local/floorplan/switch.main_lights.png?version=2E6F68A345506516D38579D5FD6579A5
        filter: none
        style:
          left: 50%
          top: 50%
          width: 100%
          mix-blend-mode: lighten
  - type: state-icon
    entity: light.shellyrgbw2_485519ebba83
    title: null
    style:
      top: 29.25%
      left: 24.15%
      border-radius: 50%
      text-align: center
      background-color: rgba(255, 255, 255, 0.3)
      opacity: 100%
    tap_action:
      action: toggle
    double_tap_action:
      action: none
    hold_action:
      action: more-info
  - type: state-icon
    entity: switch.suite_ac_power
    title: null
    style:
      top: 24.18%
      left: 10.89%
      border-radius: 50%
      text-align: center
      background-color: rgba(255, 255, 255, 0.3)
      opacity: 100%
    tap_action:
      action: toggle
    double_tap_action:
      action: none
    hold_action:
      action: more-info
  - type: state-icon
    entity: switch.main_lights
    title: null
    style:
      top: 38.44%
      left: 23.39%
      border-radius: 50%
      text-align: center
      background-color: rgba(255, 255, 255, 0.3)
      opacity: 100%
    tap_action:
      action: toggle
    double_tap_action:
      action: none
    hold_action:
      action: more-info
```
