### ISSUE TITLE
Green hue when dimmable/RGB light option is enabled

### ISSUE THREAD

**Issue by PasWeber** [shmuelzon/home-assistant-floor-plan#137]
**Describe the bug**
I am trying to display my RGB and dimmable lights in my dashbaord but they appear to have a green hue to them.
Example with 2000K temperature: 
![Image](https://github.com/user-attachments/assets/403412ab-9415-4a69-bccc-135436d4b6bd)

It gets worse the colder the temperature gets (6500K):
![Image](https://github.com/user-attachments/assets/497f2ec8-0e5f-4da3-abb7-0a2d9ca2790a)

However I am having no issues with displaying the correct colors:
![Image](https://github.com/user-attachments/assets/477e94a6-0be2-4355-89b5-cd1648db2ae3)
![Image](https://github.com/user-attachments/assets/5c424e66-e953-429d-ab26-7aec1164e049)

My setup:
- I have added a white light source in SH3D with 30% light power:
![Image](https://github.com/user-attachments/assets/3564fa79-5f85-4cc5-95b1-f7ceec15c4bd)

- These are the plugin settings:
![Image](https://github.com/user-attachments/assets/ef41e5d5-8e64-48b3-a995-c9c200b6a9bf)

- I downloaded and installed the latest release of the plugin (v0.12.1) and the config-template-card version 1.3.7-beta.1.

- I have tried with SunFlow and YafaRay, both with similar results.

- When I uncheck the "RGB/dimmable" option in the plugin, the lights look fine but now the dimming and color is not refelcted:
![Image](https://github.com/user-attachments/assets/bbe4a3cf-b10f-4034-acb1-919749a7248d)

How can i get rid of the green hue and have the lights be dimmable and with RGB?

**Comment by shmuelzon** [comment]
Hey, Is this an RGB/W light? Meaning you can configure it with an RGB color or with a white + temperature?
Can you post the state of the entity in HA when configuring the above colors? You can see them in the `Developer tools` -> `States` page. Specifically, I want to see the `color_mode`, `hs_color`, etc...

**Comment by PasWeber** [comment]
It is a Philips Hue White & Color Ambiance Lightstrip. Here is the state and the attributes:
![Image](https://github.com/user-attachments/assets/8dc88276-3f8b-435f-bd45-4ce270dac80f)

**Comment by PasWeber** [comment]
This is for red (displays correctly in the dashboard): 
![Image](https://github.com/user-attachments/assets/bdd6bdf6-05d5-46c5-9670-03e19e538312)

Purple (also no issues):
![Image](https://github.com/user-attachments/assets/ce117b66-7c09-4025-b243-455aa9fab800)

**Comment by shmuelzon** [comment]
I'm not near my PC so I can't verify but my guess is that in the color temperature mode, the generated YAML does select the 'regular' light image (and not the red-tinted one for changing colors) but since the light state still has a color setting to it, the YAML  applies the hue-rotation. I think that in this case I need to modify the code to not apply the hue rotation. That will mean that color temperature changes won't be reflected in the floor-plan but that might be better than the current alternative. Unless there's an easy way to use CSS to change the temperature like we do for color...

**Comment by PasWeber** [comment]
Thanks for your help. I guess you are talking about this section in the YAML then:
```
element:
  type: image
  image: >-
      ${COLOR_MODE === 'color_temp' || COLOR_MODE === 'brightness' || ((COLOR_MODE === 'rgb' || COLOR_MODE === 'hs') && LIGHT_COLOR && LIGHT_COLOR[0] == 0 && LIGHT_COLOR[1] == 0) ?
        '/local/floorplan/light.lightstrip_wohnzimmer.png?version=384189934801FE01794B6FF75549A42F' :
        '/local/floorplan/light.lightstrip_wohnzimmer.red.png?version=0B0DA614C888C61BD28C0170890335F8' }
style:
  filter: '${ "hue-rotate(" + (LIGHT_COLOR ? LIGHT_COLOR[0] : 0) + "deg)"}'
  opacity: '${LIGHT_STATE === ''on'' ? (BRIGHTNESS / 255) : ''100''}'
  mix-blend-mode: lighten
  pointer-events: none
  left: 50%
  top: 50%
  width: 100%
```

What would i need to change so i could verify it?
I would be fine with to not having the color temperature reflected in the image for a quick fix. 
Maybe somebody in the community here comes up with an idea on how to mix the color temperature in the future using CSS.
