### ISSUE TITLE
Add Navigate Action and Background Color Options to State-Icon

### ISSUE THREAD

**Issue by apeman4432** [shmuelzon/home-assistant-floor-plan#138]
**Is your feature request related to a problem? Please describe.**
To reduce the need for manual YAML editing, it would be helpful to expand the configuration options for tap/hold actions and styling in the UI. Specifically, for state-icon, adding support for the `navigate` action with a new field for `navigation_path` if it is selected, and including a `background-color` field for each entity.

**Describe the solution you'd like**
UI supports more action types and styling options for state-icon, resulting in YAML output like this:
```yaml
- type: state-icon
  entity: media_player.tv
  title: null
  style:
    top: 16%
    left: 40%
    border-radius: 50%
    text-align: center
    background-color: grey
    opacity: 85%
  tap_action:
    action: navigate
    navigation_path: "#family_room_tv_remote"
  double_tap_action:
    action: toggle
  hold_action:
    action: more-info
```
**Describe alternatives you've considered**
Presently requires manually editing the YAML after every render.
