### ISSUE TITLE
Error Dashboard

### ISSUE THREAD

**Issue by petroionut26** [shmuelzon/home-assistant-floor-plan#146]
After copying folder floorplan and yaml configuration i cannot save YAML woth this error:

Your configuration is not valid: r: At path: views – Expected an array value, but received: undefined.

**Comment by petroionut26** [comment]
Hy, thanks


Sent from Yahoo Mail for iPhone


On Wednesday, April 2, 2025, 4:33 PM, Assaf Inbal ***@***.***> wrote:

 
Hey, can you please share your YAML file? Either attach it here or you can email it to me directly. I'll try to see what's wrong with it

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
shmuelzon left a comment (shmuelzon/home-assistant-floor-plan#146)
Hey, can you please share your YAML file? Either attach it here or you can email it to me directly. I'll try to see what's wrong with it

**Comment by petroionut26** [comment]
type: picture-elements
image: /local/floorplan/transparent.png?version=C8A9834DE49B99CE8CA08C0B974F39B4
elements:
  - type: conditional
    conditions:
      []
    elements:
      - type: image
        tap_action:
          action: none
        hold_action:
          action: none
        image: /local/floorplan/base.png?version=9F8C636F2FA1A392849AADCD6CA143E6
        filter: none
        style:
          left: 50%
          top: 50%
          width: 100%
  - type: conditional
    conditions:
      - condition: state
        entity: switch.living_plug
        state: 'on'
    elements:
      - type: image
        tap_action:
          action: none
        hold_action:
          action: none
        image: /local/floorplan/switch.living_plug.png?version=4A3076B1349DCD42E4E8C9D8C8ECAC49
        filter: none
        style:
          left: 50%
          top: 50%
          width: 100%
          mix-blend-mode: lighten
  - type: conditional
    conditions:
      - condition: state
        entity: switch.sonoff_100216dd5f_1
        state: 'on'
    elements:
      - type: image
        tap_action:
          action: none
        hold_action:
          action: none
        image: /local/floorplan/switch.sonoff_100216dd5f_1.png?version=25AC8512FEF832E50CEB07F6DF0FCF41
        filter: none
        style:
          left: 50%
          top: 50%
          width: 100%
          mix-blend-mode: lighten
  - type: conditional
    conditions:
      - condition: state
        entity: switch.sonoff_100216dd5f_2
        state: 'on'
    elements:
      - type: image
        tap_action:
          action: none
        hold_action:
          action: none
        image: /local/floorplan/switch.sonoff_100216dd5f_2.png?version=0F176E59D2F17720B2F15C4F58D3E5C0
        filter: none
        style:
          left: 50%
          top: 50%
          width: 100%
          mix-blend-mode: lighten
  - type: conditional
    conditions:
      - condition: state
        entity: light.yeelink_lamp4_5ec0_light
        state: 'on'
    elements:
      - type: image
        tap_action:
          action: none
        hold_action:
          action: none
        image: /local/floorplan/light.yeelink_lamp4_5ec0_light.png?version=E42AF8E6B162ADBECC688D92B05E5073
        filter: none
        style:
          left: 50%
          top: 50%
          width: 100%
          mix-blend-mode: lighten
  - type: conditional
    conditions:
      - condition: state
        entity: switch.kitchen_plug
        state: 'on'
    elements:
      - type: image
        tap_action:
          action: none
        hold_action:
          action: none
        image: /local/floorplan/switch.kitchen_plug.png?version=EC57334F1D93F5E8CE1E4DD5399650D2
        filter: none
        style:
          left: 50%
          top: 50%
          width: 100%
          mix-blend-mode: lighten
  - type: state-icon
    entity: switch.living_plug
    title: null
    style:
      top: 27.01%
      left: 37.91%
      border-radius: 50%
      text-align: center
      background-color: rgba(255, 255, 255, 0.3)
      opacity: 100%
    tap_action:
      action: toggle
    double_tap_action:
      action: none
    hold_action:
      action: more-info
  - type: state-icon
    entity: switch.sonoff_100216dd5f_1
    title: null
    style:
      top: 51.17%
      left: 39.48%
      border-radius: 50%
      text-align: center
      background-color: rgba(255, 255, 255, 0.3)
      opacity: 100%
    tap_action:
      action: toggle
    double_tap_action:
      action: none
    hold_action:
      action: more-info
  - type: state-icon
    entity: switch.sonoff_100216dd5f_2
    title: null
    style:
      top: 35.35%
      left: 40.02%
      border-radius: 50%
      text-align: center
      background-color: rgba(255, 255, 255, 0.3)
      opacity: 100%
    tap_action:
      action: toggle
    double_tap_action:
      action: none
    hold_action:
      action: more-info
  - type: state-icon
    entity: light.yeelink_lamp4_5ec0_light
    title: null
    style:
      top: 27.97%
      left: 45.42%
      border-radius: 50%
      text-align: center
      background-color: rgba(255, 255, 255, 0.3)
      opacity: 100%
    tap_action:
      action: toggle
    double_tap_action:
      action: none
    hold_action:
      action: more-info
  - type: state-icon
    entity: switch.kitchen_plug
    title: null
    style:
      top: 69.84%
      left: 46.04%
      border-radius: 50%
      text-align: center
      background-color: rgba(255, 255, 255, 0.3)
      opacity: 100%
    tap_action:
      action: toggle
    double_tap_action:
      action: none
    hold_action:
      action: more-info

**Comment by shmuelzon** [comment]
Can you please either attach it as a file here or paste the contents in a code block. For the latter, you need to create a comment like:
````
```
<paste here>
```
````
That way, GitHub will retain the format of the YAML. As it is right now, I can't copy it

**Comment by petroionut26** [comment]
Ok, thanks for your time! I hope it’s ok now.


```

type: picture-elements
image: /local/floorplan/transparent.png?version=C8A9834DE49B99CE8CA08C0B974F39B4
elements:
  - type: conditional
    conditions:
      []
    elements:
      - type: image
        tap_action:
          action: none
        hold_action:
          action: none
        image: /local/floorplan/base.png?version=9F8C636F2FA1A392849AADCD6CA143E6
        filter: none
        style:
          left: 50%
          top: 50%
          width: 100%
  - type: conditional
    conditions:
      - condition: state
        entity: switch.living_plug
        state: 'on'
    elements:
      - type: image
        tap_action:
          action: none
        hold_action:
          action: none
        image: /local/floorplan/switch.living_plug.png?version=4A3076B1349DCD42E4E8C9D8C8ECAC49
        filter: none
        style:
          left: 50%
          top: 50%
          width: 100%
          mix-blend-mode: lighten
  - type: conditional
    conditions:
      - condition: state
        entity: switch.sonoff_100216dd5f_1
        state: 'on'
    elements:
      - type: image
        tap_action:
          action: none
        hold_action:
          action: none
        image: /local/floorplan/switch.sonoff_100216dd5f_1.png?version=25AC8512FEF832E50CEB07F6DF0FCF41
        filter: none
        style:
          left: 50%
          top: 50%
          width: 100%
          mix-blend-mode: lighten
  - type: conditional
    conditions:
      - condition: state
        entity: switch.sonoff_100216dd5f_2
        state: 'on'
    elements:
      - type: image
        tap_action:
          action: none
        hold_action:
          action: none
        image: /local/floorplan/switch.sonoff_100216dd5f_2.png?version=0F176E59D2F17720B2F15C4F58D3E5C0
        filter: none
        style:
          left: 50%
          top: 50%
          width: 100%
          mix-blend-mode: lighten
  - type: conditional
    conditions:
      - condition: state
        entity: light.yeelink_lamp4_5ec0_light
        state: 'on'
    elements:
      - type: image
        tap_action:
          action: none
        hold_action:
          action: none
        image: /local/floorplan/light.yeelink_lamp4_5ec0_light.png?version=E42AF8E6B162ADBECC688D92B05E5073
        filter: none
        style:
          left: 50%
          top: 50%
          width: 100%
          mix-blend-mode: lighten
  - type: conditional
    conditions:
      - condition: state
        entity: switch.kitchen_plug
        state: 'on'
    elements:
      - type: image
        tap_action:
          action: none
        hold_action:
          action: none
        image: /local/floorplan/switch.kitchen_plug.png?version=EC57334F1D93F5E8CE1E4DD5399650D2
        filter: none
        style:
          left: 50%
          top: 50%
          width: 100%
          mix-blend-mode: lighten
  - type: state-icon
    entity: switch.living_plug
    title: null
    style:
      top: 27.01%
      left: 37.91%
      border-radius: 50%
      text-align: center
      background-color: rgba(255, 255, 255, 0.3)
      opacity: 100%
    tap_action:
      action: toggle
    double_tap_action:
      action: none
    hold_action:
      action: more-info
  - type: state-icon
    entity: switch.sonoff_100216dd5f_1
    title: null
    style:
      top: 51.17%
      left: 39.48%
      border-radius: 50%
      text-align: center
      background-color: rgba(255, 255, 255, 0.3)
      opacity: 100%
    tap_action:
      action: toggle
    double_tap_action:
      action: none
    hold_action:
      action: more-info
  - type: state-icon
    entity: switch.sonoff_100216dd5f_2
    title: null
    style:
      top: 35.35%
      left: 40.02%
      border-radius: 50%
      text-align: center
      background-color: rgba(255, 255, 255, 0.3)
      opacity: 100%
    tap_action:
      action: toggle
    double_tap_action:
      action: none
    hold_action:
      action: more-info
  - type: state-icon
    entity: light.yeelink_lamp4_5ec0_light
    title: null
    style:
      top: 27.97%
      left: 45.42%
      border-radius: 50%
      text-align: center
      background-color: rgba(255, 255, 255, 0.3)
      opacity: 100%
    tap_action:
      action: toggle
    double_tap_action:
      action: none
    hold_action:
      action: more-info
  - type: state-icon
    entity: switch.kitchen_plug
    title: null
    style:
      top: 69.84%
      left: 46.04%
      border-radius: 50%
      text-align: center
      background-color: rgba(255, 255, 255, 0.3)
      opacity: 100%
    tap_action:
      action: toggle
    double_tap_action:
      action: none
    hold_action:
      action: more-info

```
