### ISSUE TITLE
Add title attribute for each condition block

### ISSUE THREAD

**Issue by BobMcCloy** [shmuelzon/home-assistant-floor-plan#151]
Hi,
first of all, thanks for this great project!

I have a small feature request:
Would it be possible to allow defining a title or label attribute for each condition entry in the floorplan YAML config?

For example, when using many conditions—each linked to a different image or state—it would be super helpful to include a descriptive title like the image name. This would make it much easier to find and edit specific conditions later, especially when working in Home Assistant's GUI mode or reviewing YAML files manually.

Example:

```
type: conditional
conditions: []
elements:
  - type: image
    tap_action:
      action: none
    hold_action:
      action: none
    image: /local/floorplanOG/base.png?version=1223A6821257A7D884FCCEBF216D178F
    filter: none
    style:
      left: 50%
      top: 50%
      width: 100%
title: base.png
```

This wouldn’t affect functionality but would greatly improve usability and clarity in complex setups.

Thanks for considering!
