### ISSUE TITLE
Wrong icon location and changing depending on render resolution

### ISSUE THREAD

**Issue by richard-kramer** [shmuelzon/home-assistant-floor-plan#82]
**Describe the bug**

When creating the interactive floor plan, the entity icons don't get placed, where their respective objects are in the 3D plan.

I recreated the error with one of the SH3D test plans.

![image](https://github.com/user-attachments/assets/e812df14-4544-496c-84eb-eb1dad8977ae)

Resulting YAML:

```yaml
type: picture-elements
image: /local/floorplan/base.png?version=3E581E0D91A79E49C58129C9BD5C9CF6
elements:
  - type: conditional
    conditions:
      - entity: light.office_pendant_light
        state: 'on'
    elements:
      - type: image
        tap_action:
          action: none
        hold_action:
          action: none
        entity:
          - light.office_pendant_light
        image: /local/floorplan/light.office_pendant_light.png?version=337CB257924348A75F7671C415E709FE
        filter: none
        style:
          left: 50%
          top: 50%
          width: 100%
          mix-blend-mode: lighten
  - type: state-icon
    entity: light.office_pendant_light
    title: null
    style:
      top: 109.84%
      left: 63.63%
      border-radius: 50%
      text-align: center
      background-color: rgba(255, 255, 255, 0.3)
    tap_action:
      action: toggle
```

Screenshot of the card in HA (entity icon missing entirely, because with 109% ``top`` value it's outside the bounding box)

![image](https://github.com/user-attachments/assets/f7fa5b99-38b4-4a99-a518-34c18f42714b)

**To Reproduce**

1. Open test.sh3d from [test.zip](https://github.com/user-attachments/files/17100723/test.zip)
   
   The hanging light above the round table in the livingroom should be named `light.office_pendant_light` (thats the entity I mapped it to for this example). All other lights should be hidden
3. Place camera above the whole plan looking down (more or less the default location)
4. Export floor plan with plugin; width `600`, height `437` (this size was a fitting aspect ratio to show the whole floor without extra whitespace and relatively small to do a fast render), quality `low`
5. Check the created YAML.

**Expected behavior**

The `state-icon` should be placed above the lamp in the image. But the `top` and `left` postition are nowhere near (`top` being over 100% and out of the image alltogether).

I would also expect the YAML to not change if I change the resolution but keep the aspect ratio and camera settings, as the objects should be in the exact same location relative to the camera.

**Additional context**

- I had this problem when creating an export with the actual plan of my apartment in low resultution but also in a higher one.
- The icon position was closest when rendering with a width around the `1000` mark. But also not on point.
- the position seems to be influenced by other lights. I rendered the plan with one additional light (the desk lamp ("Schreibtischlampe") in the bedroom 3) and got this YAML. Positioning is absolutely wild.
   
    ```yaml
    type: picture-elements
    image: /local/floorplan/base.png?version=0372A8AF6E9C7F2F01576910DAC69FAC
    elements:
      - type: conditional
        conditions:
          - entity: light.office_pendant_light
            state: 'on'
        elements:
          - type: image
            tap_action:
              action: none
            hold_action:
              action: none
            entity:
              - light.office_pendant_light
            image: /local/floorplan/light.office_pendant_light.png?version=F8E0AA5BE815DE18D66E0F32764C6A13
            filter: none
            style:
              left: 50%
              top: 50%
              width: 100%
              mix-blend-mode: lighten
      - type: conditional
        conditions:
          - entity: light.office_overhead_light
            state: 'on'
        elements:
          - type: image
            tap_action:
              action: none
            hold_action:
              action: none
            entity:
              - light.office_overhead_light
            image: /local/floorplan/light.office_overhead_light.png?version=7483E0BE428D0EBABA7D2CBE002018BA
            filter: none
            style:
              left: 50%
              top: 50%
              width: 100%
              mix-blend-mode: lighten
      - type: state-icon
        entity: light.office_pendant_light
        title: null
        style:
          top: 252.52%
          left: 124.27%
          border-radius: 50%
          text-align: center
          background-color: rgba(255, 255, 255, 0.3)
        tap_action:
          action: toggle
      - type: state-icon
        entity: light.office_overhead_light
        title: null
        style:
          top: 187.88%
          left: 270.20%
          border-radius: 50%
          text-align: center
          background-color: rgba(255, 255, 255, 0.3)
        tap_action:
          action: toggle
    ```
- I tried it again after closing and reopening the file (because I wanted to add a screenshot from HA) in SH3D and now the placements are correct. I did not touch the camera again, as it was positioned where I left it the first time. So maybe it's a problem with first configuring the plan for teh export and placing the camera?
